version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - FRONTEND_URL=http://happsrv.mooo.com:5173
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - AI_API_URL=http://ai:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - VITE_BACKEND_URL=http://happsrv.mooo.com:8000
    ports:
      - "5173:5173"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: tg_bot
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:8000
      - FRONTEND_URL=http://happsrv.mooo.com:5173
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    restart: unless-stopped
    ports:
      - "9000:8000"

volumes:
  postgres_data: